version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://localhost:8080
    restart: always
  backend:
    image: backend:latest
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:3000
      - POSTGRES_HOST=db
      - POSTGRES_USER=frontend_backend
      - POSTGRES_DATABASE=frontend_backend_database
      - POSTGRES_PASSWORD=helloworld1234
    restart: always
  db:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=frontend_backend
      - POSTGRES_DB=frontend_backend_database
      - POSTGRES_PASSWORD=helloworld1234
    restart: always