name: Pull Request CI Pipeline

on:
  pull_request:
    types: [synchronize, opened]

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker build . -t docker.pkg.github.com/dernat71/example-cicd/my-example-fastapi-endpoint:$git_hash

    - name: Test the Docker image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker run \
        --entrypoint=/bin/bash \
        docker.pkg.github.com/dernat71/example-cicd/my-example-fastapi-endpoint:$git_hash \
        ./script/test